[package]
name = "narwhal-crypto"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
fastcrypto.workspace = true
ark-bls12-377 = { version = "0.3.0", features = ["std"], optional = true }
eyre = "0.6.8"
rand = { version = "0.8.5", features = ["std"] }
serde = { version = "1.0.144", features = ["derive"] }
shared-crypto = { path = "../../crates/shared-crypto"}
bcs = "0.1.4"

[features]
default = []
[dev-dependencies]
bincode = "1.3.3"
criterion = "0.4.0"
hex-literal = "0.3.4"
proptest = "1.0.0"
proptest-derive = "0.3.0"
serde_json = "1.0.88"
serde-reflection = "0.3.6"
