[package]
name = "narwhal-consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[features]
default = ["rand"]
metrics = ["dep:metrics", "dep:snarkos-metrics"]
pprof = []

[dependencies]

# crates.io dependencies
arc-swap = { version = "1.5.1", features = ["serde"] }
bincode = "1.3.3"
bytes = "1.3.0"
cfg-if = "1.0.0"
match_opt = "0.1.2"
rand = { version = "0.8.5", optional = true }
thiserror = "1.0.35"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1.36"

# internal dependencies
config = { path = "../config", package = "narwhal-config" }
crypto = { path = "../crypto", package = "narwhal-crypto" }
dag = { path = "../dag", package = "narwhal-dag" }
fastcrypto = { workspace = true }
mysten-util-mem = { path = "../../crates/mysten-util-mem" }
storage = { path = "../storage", package = "narwhal-storage" }
store = { path = "../../crates/typed-store", package = "typed-store" }
types = { path = "../types", package = "narwhal-types" }

[dependencies.metrics]
workspace = true
optional = true

[dependencies.snarkos-metrics]
workspace = true
optional = true

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.4.0"
futures = "0.3.24"
indexmap = { version = "1.9.2", features = ["serde"] }
telemetry-subscribers = { path = "../../crates/telemetry-subscribers" }
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
node = { path = "../node", package = "narwhal-node" }

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11.0", features = ["criterion", "flamegraph"]}

[lib]
bench = false

