[package]
name = "narwhal-consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
bcs = "0.1.4"
match_opt = "0.1.2"
rand = { version = "0.8.5", optional = true }
thiserror = "1.0.35"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1.36"

config = { path = "../config", package = "narwhal-config" }
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "235211dc8195590f5353d38135f5ee51a267521e" }
crypto = { path = "../crypto", package = "narwhal-crypto" }
storage = { path = "../storage", package = "narwhal-storage" }
dag = { path = "../dag", package = "narwhal-dag" }
types = { path = "../types", package = "narwhal-types" }
cfg-if = "1.0.0"
mysten-util-mem = { path = "../../crates/mysten-util-mem" }
store = { path = "../../crates/typed-store", package = "typed-store" }

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.4.0"
futures = "0.3.24"
indexmap = { version = "1.9.2", features = ["serde"] }
telemetry-subscribers = { path = "../../crates/telemetry-subscribers" }
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
node = { path = "../node", package = "narwhal-node" }

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11.0", features = ["criterion", "flamegraph"]}

[features]
default = ["rand"]
pprof = []

[lib]
bench = false

