[package]
name = "narwhal-network"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
metrics.workspace = true
snarkos-metrics.workspace = true
async-trait = "0.1.61"
backoff = { version = "0.4.0", features = ["tokio"] }
bytes = "1.3.0"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "235211dc8195590f5353d38135f5ee51a267521e" }
futures = "0.3.24"
multiaddr = "0.17.0"
rand = { version = "0.8.5", features = ["small_rng"] }
thiserror = "1.0.35"
tokio = { version = "1", features = ["rt", "net", "sync", "macros", "time"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = { version = "0.8.2", features = ["tls"] }
tracing = "0.1.36"
types = { path = "../types", package = "narwhal-types" }
crypto = { path = "../crypto", package = "narwhal-crypto" }

serde = "1.0.144"
eyre = "0.6.8"

anemo = { git = "https://github.com/mystenlabs/anemo.git", rev = "0e0ef7054082a6f5a8921688e3d568761bc3be21" }
anemo-tower = { git = "https://github.com/mystenlabs/anemo.git", rev = "0e0ef7054082a6f5a8921688e3d568761bc3be21" }
anyhow = "1.0.65"
axum.workspace = true
axum-server = "0.4.2"
tower = "0.4.13"

[dev-dependencies]
bincode = "1.3.3"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
