[package]
name = "narwhal-node"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
async-trait = "0.1.61"
bytes = "1.3.0"
cfg-if = "1.0.0"
clap = "2.34"
futures = "0.3.24"
rand = "0.8.5"
thiserror = "1.0.35"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.10"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", default-features = false, features = ["std", "smallvec", "fmt", "ansi", "time", "env-filter"] }
url = "2.3.1"
axum.workspace = true

anyhow = { version = "1.0.64", features = ["backtrace"] }
config = { path = "../config", package = "narwhal-config" }
consensus = { path = "../consensus", package = "narwhal-consensus" }
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "235211dc8195590f5353d38135f5ee51a267521e" }
crypto = { path = "../crypto", package = "narwhal-crypto" }
executor = { path = "../executor", package = "narwhal-executor" }
network = { path = "../network", package = "narwhal-network" }
primary = { path = "../primary", package = "narwhal-primary" }
prometheus = "0.13.3"
storage = { path = "../storage", package = "narwhal-storage" }
types = { path = "../types", package = "narwhal-types" }
worker = { path = "../worker", package = "narwhal-worker" }
eyre = "0.6.8"
serde = {version = "1.0.144", features = ["derive"]}
roaring = "0.10.1"
enum_dispatch = "^0.3"
schemars ="0.8.10"
derive_more = "0.99.17"
serde_with = "2.1.0"
signature = "1.6.0"
strum = "^0.24"
strum_macros = "^0.24"

mysten-metrics = { path = "../../crates/mysten-metrics" }
store = { path = "../../crates/typed-store", package = "typed-store" }
mysten-network = { path = "../../crates/mysten-network" }
telemetry-subscribers = { path = "../../crates/telemetry-subscribers" }

anemo = { git = "https://github.com/mystenlabs/anemo.git", rev = "0e0ef7054082a6f5a8921688e3d568761bc3be21" }
reqwest = { version = "0.11.13", features = ["json"] }
once_cell = "1.16.0"
fail = "0.5.1"

[dev-dependencies]
pretty_assertions = "1.3.0"
serde-reflection = "0.3.6"
serde_yaml = "0.8.26"
structopt = "0.3.26"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }

[features]
benchmark = ["worker/benchmark", "primary/benchmark", "consensus/benchmark"]
trace_transaction = ["worker/trace_transaction"]

[[bin]]
name = "narwhal-node"
path = "src/main.rs"

[[bin]]
name = "narwhal-benchmark-client"
path = "src/benchmark_client.rs"
required-features = ["benchmark"]

[[example]]
name = "narwhal-generate-format"
path = "src/generate_format.rs"
test = false
