[package]
name = "narwhal-worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
arc-swap = "1.5.1"
async-trait = "0.1.61"
bincode = "1.3.3"
bytes = "1.3.0"
futures = "0.3.24"
governor = "0.5.1"
rand = { version = "0.8.5", features = ["small_rng"] }
tap = "1.0.1"
tokio = { version = "1", features = ["sync", "rt", "macros"] }
tokio-stream = "0.1.10"
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = "0.8.2"
tower = "0.4.13"
tracing = "0.1.36"
itertools = "0.10.5"

config = { path = "../config", package = "narwhal-config" }
fastcrypto = { workspace = true }
crypto = { path = "../crypto", package = "narwhal-crypto" }
network = { path = "../network", package = "narwhal-network" }
types = { path = "../types", package = "narwhal-types" }
store = { path = "../../crates/typed-store", package = "typed-store" }
mysten-network.workspace = true

anemo = { git = "https://github.com/mystenlabs/anemo.git", rev = "0e0ef7054082a6f5a8921688e3d568761bc3be21" }
anemo-tower = { git = "https://github.com/mystenlabs/anemo.git", rev = "0e0ef7054082a6f5a8921688e3d568761bc3be21" }
anyhow = "1.0.65"
eyre = "0.6.8"

[dev-dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
rand = "0.8.5"
tempfile = "3.4.0"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
reqwest = { version = "0.11.13", default_features= false, features = ["json", "rustls-tls"] }
node = { path = "../node", package = "narwhal-node" }
consensus = { path = "../consensus", package = "narwhal-consensus" }
primary = { path = "../primary", package = "narwhal-primary" }
telemetry-subscribers = { path = "../../crates/telemetry-subscribers"}
storage = { path = "../storage", package = "narwhal-storage" }
