[package]
name = "narwhal-test-utils"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false

[dependencies]
fdlimit = "0.2"
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
prometheus = "0.13.3"
rand = "0.8.5"
tempfile = "3.3.0"
thiserror = "1.0.35"
tokio = { version = "1", features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = "0.8.2"
tracing = "0.1.36"
once_cell = "1.16"

config = { path = "../config", package = "narwhal-config" }
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "235211dc8195590f5353d38135f5ee51a267521e" }
crypto = { path = "../crypto", package = "narwhal-crypto" }
executor = { path = "../executor", package = "narwhal-executor" }
network = { path = "../network", package = "narwhal-network" }
node = { path = "../node", package = "narwhal-node" }
primary = { path = "../primary", package = "narwhal-primary" }
types = { path = "../types", package = "narwhal-types" }
worker = { path = "../worker", package = "narwhal-worker" }
storage = { path = "../storage", package = "narwhal-storage" }
mysten-metrics = { path = "../../crates/mysten-metrics" }
store = { path = "../../crates/typed-store", package = "typed-store" }
telemetry-subscribers = { path = "../../crates/telemetry-subscribers", package = "telemetry-subscribers" }
mysten-network = { path = "../../crates/mysten-network" }

anemo = { git = "https://github.com/mystenlabs/anemo.git", rev = "0e0ef7054082a6f5a8921688e3d568761bc3be21" }
tower = { version = "0.4.13", features = ["full"] }
once_cell = "1.16.0"
