[package]
name = "mysten-common"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio.workspace = true
futures = "0.3.23"
parking_lot = "0.12.1"