[package]
name = "narwhal-types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false

[dependencies]
async-trait = "0.1.61"
base64 = "0.13.0"
bcs = "0.1.4"
bytes = "1.3.0"
derive_builder = "0.12.0"
enum_dispatch = "^0.3"
futures = "0.3.24"
indexmap = { version = "1.9.2", features = ["serde"] }
mockall = "0.11.2"
proptest = "1.0.0"
proptest-derive = "0.3.0"
prost = "0.11.3"
rand = "0.8.5"
roaring = "0.10.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_with = "2.1.0"
thiserror = "1.0.35"
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = { version = "0.8.2", features = ["tls"] }
tracing = "0.1.36"

config = { path = "../config", package = "narwhal-config" }
fastcrypto.workspace = true
crypto = { path = "../crypto", package = "narwhal-crypto" }
dag = { path = "../dag", package = "narwhal-dag" }
anemo.workspace = true
once_cell = "1.16.0"

store = { path = "../../crates/typed-store", package = "typed-store" }
mysten-network.workspace = true
mysten-common.workspace = true

[dependencies.snarkvm-console]
version = "0.9.14"

[dev-dependencies]
serde_test = "1.0.147"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
criterion = "0.5.1"
pprof = { version = "0.11.1", features = ["cpp", "frame-pointer", "criterion", "flamegraph"] }

[target.'cfg(not(target_env = "msvc"))'.build-dependencies]
protobuf-src = "1.1.0"

[build-dependencies]
prost-build = "0.11.1"
rustversion = "1.0.9"
tonic-build = { version = "0.8.2", features = [ "prost", "transport" ] }
anemo-build = { git = "https://github.com/mystenlabs/anemo.git", rev = "0e0ef7054082a6f5a8921688e3d568761bc3be21" }

[features]
default = []
test = []
